// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for DownloadFunction
 */
export interface DownloadFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/app/download/download.
 */
export class DownloadFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: DownloadFunctionProps) {
    super(scope, id, {
      description: 'src/app/download/download.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/app/download/download.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}