// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for Migration20240206EnrichTableFunction
 */
export interface Migration20240206EnrichTableFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/migrations/migration-2024-02-06-enrich-table.
 */
export class Migration20240206EnrichTableFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: Migration20240206EnrichTableFunctionProps) {
    super(scope, id, {
      description: 'src/migrations/migration-2024-02-06-enrich-table.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/migrations/migration-2024-02-06-enrich-table.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}